source 'https://rubygems.org'

gem 'english', '= 0.7.0'
gem 'faraday', '= 0.17.3'
gem 'faraday-net_http', '<= 2.1.0'
gem 'minitest', '= 5.15.0'
gem 'minitest-reporters'
gem 'netrc', '= 0.11.0'
gem 'octokit', '= 4.14.0'
gem 'public_suffix', '<= 4.0.7'
gem 'rake'
gem 'reek'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'
